config ={
   'version':'v1',
   'config':{
      'visState':{
         'filters':[

         ],
         'layers':[
            {
               'id':'kjyucbb',
               'type':'hexagon',
               'config':{
                  'dataId':'stations',
                  'label':'Point',
                  'color':[
                     246,
                     209,
                     138
                  ],
                  'columns':{
                     'lat':'lat',
                     'lng':'lng'
                  },
                  'isVisible':True,
                  'visConfig':{
                     'opacity':0.25,
                     'worldUnitSize':0.2,
                     'resolution':8,
                     'colorRange':{
                        'name':'Uber Viz Diverging 0.5',
                        'type':'diverging',
                        'category':'Uber',
                        'colors':[
                           '#C22E00',
                           '#EFBEAE',
                           '#A2D4D7',
                           '#00939C'
                        ],
                        'reversed':True
                     },
                     'coverage':1,
                     'sizeRange':[
                        0,
                        500
                     ],
                     'percentile':[
                        0.05,
                        100
                     ],
                     'elevationPercentile':[
                        0,
                        100
                     ],
                     'elevationScale':5.7,
                     'colorAggregation':'sum',
                     'sizeAggregation':'count',
                     'enable3d':True
                  },
                  'textLabel':[
                     {
                        'field':None,
                        'color':[
                           255,
                           255,
                           255
                        ],
                        'size':18,
                        'offset':[
                           0,
                           0
                        ],
                        'anchor':'start',
                        'alignment':'center'
                     }
                  ]
               },
               'visualChannels':{
                  'colorField':{
                     'name':'nbebike',
                     'type':'integer'
                  },
                  'colorScale':'quantile',
                  'sizeField':None,
                  'sizeScale':'linear'
               }
            },
            {
               'id':'u5viubu',
               'type':'geojson',
               'config':{
                  'dataId':'districts',
                  'label':'districts',
                  'color':[
                     248,
                     149,
                     112
                  ],
                  'columns':{
                     'geojson':'geometry'
                  },
                  'isVisible':True,
                  'visConfig':{
                     'opacity':0.8,
                     'thickness':0.5,
                     'strokeColor':[
                        130,
                        154,
                        227
                     ],
                     'colorRange':{
                        'name':'Global Warming',
                        'type':'sequential',
                        'category':'Uber',
                        'colors':[
                           '#5A1846',
                           '#900C3F',
                           '#C70039',
                           '#E3611C',
                           '#F1920E',
                           '#FFC300'
                        ]
                     },
                     'strokeColorRange':{
                        'name':'Global Warming',
                        'type':'sequential',
                        'category':'Uber',
                        'colors':[
                           '#5A1846',
                           '#900C3F',
                           '#C70039',
                           '#E3611C',
                           '#F1920E',
                           '#FFC300'
                        ]
                     },
                     'radius':10,
                     'sizeRange':[
                        0,
                        10
                     ],
                     'radiusRange':[
                        0,
                        50
                     ],
                     'heightRange':[
                        0,
                        500
                     ],
                     'elevationScale':5,
                     'stroked':True,
                     'filled':True,
                     'enable3d':False,
                     'wireframe':False
                  },
                  'textLabel':[
                     {
                        'field':None,
                        'color':[
                           255,
                           255,
                           255
                        ],
                        'size':18,
                        'offset':[
                           0,
                           0
                        ],
                        'anchor':'start',
                        'alignment':'center'
                     }
                  ]
               },
               'visualChannels':{
                  'colorField':None,
                  'colorScale':'quantile',
                  'sizeField':None,
                  'sizeScale':'linear',
                  'strokeColorField':None,
                  'strokeColorScale':'quantile',
                  'heightField':None,
                  'heightScale':'linear',
                  'radiusField':None,
                  'radiusScale':'linear'
               }
            }
         ],
         'interactionConfig':{
            'tooltip':{
               'fieldsToShow':{
                  'stations':[
                     'nbfreeedock',
                     'nbebike',
                     'station_state',
                     'maxbikeoverflow',
                     'nbedock'
                  ],
                  'districts':[
                     'n_sq_qu',
                     'n_sq_ar',
                     'c_qu',
                     'surface',
                     'l_qu'
                  ]
               },
               'enabled':False
            },
            'brush':{
               'size':0.5,
               'enabled':False
            }
         },
         'layerBlending':'normal',
         'splitMaps':[

         ],
         'animationConfig':{
            'currentTime':None,
            'speed':1
         }
      },
      'mapState':{
         'bearing':-11.415821501014204,
         'dragRotate':True,
         'latitude':48.85821626124779,
         'longitude':2.3205259012289448,
         'pitch':34.770177432142525,
         'zoom':10.250556172164764,
         'isSplit':False
      },
      'mapStyle':{
         'styleType':'light',
         'topLayerGroups':{

         },
         'visibleLayerGroups':{
            'label':True,
            'road':True,
            'border':False,
            'building':True,
            'water':True,
            'land':True,
            '3d building':False
         },
         'threeDBuildingColor':[
            218.82023004728686,
            223.47597962276103,
            223.47597962276103
         ],
         'mapStyles':{

         }
      }
   }
}