service:
  type: ClusterIP

config:
  BinderHub:
    debug: true
    use_registry: false
    image_prefix: "binderhub-images-"
    hub_url: 'http://proxy-public'

jupyterhub:
  hub:
    services:
      binder:
        apiToken: "0581f345e93fc5ebf645d1de713dd87e2f0d3949ab831b7f0f03830021653286"
    db:
      type: "sqlite-memory"
  proxy:
    secretToken: "b1510747ecc49423f7a05d6d31f2abd30413d669255f995a833754a4a12b991e"
    service:
      type: ClusterIP


imageCleaner:
  enabled: false