hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

proxy:
  secretToken: '55a814cdf1b3eb163833bf2e6264f3992e7eb0143ececf434f496deb6daf00dc'

singleuser:
  extraTolerations: []
  extraEnv:
    AWS_ACCESS_KEY_ID: minio
    AWS_SECRET_ACCESS_KEY: minio123
    AWS_S3_ENDPOINT: http://minio:9000/
  default_url: "/lab/"
  image:
    name: xebicon19_velib
    tag: latest
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      default: true
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      default: true
    - display_name: "Learning Data Science"
      description: "Datascience Environment with Sample Notebooks"
      default: true
