## Set default accesskey, secretkey, Minio config file path, volume mount path and
## number of nodes (only used for Minio distributed mode)
## AccessKey and secretKey is generated when not set
## Distributed Minio ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
##
accessKey: "minio"
secretKey: "minio123"

## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  size: 10Gi

## Create multiple buckets after minio install
## Enabling `defaultBucket` will take priority over this list
##
buckets:
  - name: velib-usage
    policy: none
    purge: false
  - name: smovengo
    policy: none
    purge: false

ingress:
  enabled: true
  hosts:
    - minio.local
  annotations:
    kubernetes.io/ingress.class: traefik