## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  tag: RELEASE.2019-08-07T01-59-21Z

mcImage:
  tag: RELEASE.2019-08-07T23-14-43Z

## minio server mode, i.e. standalone or distributed.
## Distributed Minio ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
##
mode: standalone

## Set default accesskey, secretkey, Minio config file path, volume mount path and
## number of nodes (only used for Minio distributed mode)
## AccessKey and secretKey is generated when not set
## Distributed Minio ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
##
accessKey: "minio"
secretKey: "minio123"

## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  size: 10Gi

## Create multiple buckets after minio install
## Enabling `defaultBucket` will take priority over this list
##
buckets:
  - name: bookstore
    policy: none
    purge: false